/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "secondary": "#565e74",
        "tertiary-container": "#707579",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#dae2fd",
        "primary-fixed": "#e1e0ff",
        "background": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#5c647a",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed-variant": "#43474b",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "primary": "#6366f1", // Updated to requested primary
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#c0c1ff",
        "on-secondary-fixed": "#131b2e",
        "inverse-surface": "#213145",
        "tertiary": "#585d60",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#fbfcff",
        "surface-container-high": "#dce9ff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface-variant": "#464554",
        "outline": "#767586",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#dfe3e7",
        "surface-tint": "#494bd6",
        "surface": "#f8f9ff",
        "outline-variant": "#c7c4d7",
        "secondary-container": "#dae2fd",
        "surface-container-highest": "#d3e4fe",
        "primary-container": "#6063ee",
        "on-tertiary-fixed": "#171c1f",
        "on-surface": "#0b1c30"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1200px",
        "base": "4px",
        "xxl": "48px",
        "lg": "24px",
        "margin-mobile": "16px",
        "sm": "8px",
        "xs": "4px",
        "md": "16px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "xl": "32px"
      },
      "fontFamily": {
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "title-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "label-sm": ["Geist"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}

