import "dotenv/config";

import app from "./app.ts";
import sequelize from "./config/db.ts";
import "./model/media.model.ts";
import blogs from "./model/blog.model.ts";
import { getCategoryForBlog } from "./utils/category.utils.ts";

import { initCronJobs } from "./config/cron.ts";

async function backfillCategories() {
  try {
    const unclassifiedBlogs = await blogs.findAll({
      where: {
        category: null
      }
    });
    if (unclassifiedBlogs.length > 0) {
      console.log(`⏳ Found ${unclassifiedBlogs.length} unclassified blogs. Starting backfill...`);
      for (const blog of unclassifiedBlogs) {
        const title = blog.getDataValue("title");
        const content = blog.getDataValue("content");
        const category = getCategoryForBlog(title, content);
        await blog.update({ category });
      }
      console.log("✅ Backfill completed successfully.");
    } else {
      console.log("✅ No unclassified blogs found.");
    }
  } catch (err) {
    console.error("❌ Failed to backfill blog categories:", err);
  }
}

async function deduplicateUsernames() {
  try {
    const [results] = await sequelize.query(
      "SELECT username, COUNT(*) as count FROM users GROUP BY username HAVING count > 1"
    );
    if (results.length > 0) {
      console.log(`⏳ Found ${results.length} duplicate usernames in DB. Starting self-healing deduplication...`);
      for (const row of (results as any[])) {
        const username = row.username;
        const [users] = await sequelize.query(
          "SELECT id FROM users WHERE username = :username ORDER BY id ASC",
          { replacements: { username } }
        );
        for (let i = 1; i < (users as any[]).length; i++) {
          const user = (users as any[])[i];
          const newUsername = `${username}_${user.id}`;
          console.log(`👉 Renaming duplicate user ID ${user.id} from "${username}" to "${newUsername}"`);
          await sequelize.query(
            "UPDATE users SET username = :newUsername WHERE id = :id",
            { replacements: { newUsername, id: user.id } }
          );
        }
      }
      console.log("✅ Username deduplication completed successfully.");
    }
  } catch (err: any) {
    console.log("ℹ️ Skipping username deduplication (table might not exist yet):", err.message);
  }
}

async function cleanupDuplicateIndexes() {
  try {
    const [indexes] = await sequelize.query("SHOW INDEX FROM users");
    const indexNames = new Set((indexes as any[]).map(idx => idx.Key_name));
    const seenBase = new Set<string>();

    for (const keyName of indexNames) {
      if (keyName === "PRIMARY") continue;

      const isEmailKey = keyName.startsWith("email") || keyName.includes("email");
      const isUsernameKey = keyName.startsWith("username") || keyName.includes("username");
      const isPhoneKey = keyName.startsWith("phoneNumber") || keyName.includes("phone");

      if (isEmailKey || isUsernameKey || isPhoneKey) {
        let baseType = "";
        if (isEmailKey) baseType = "email";
        else if (isUsernameKey) baseType = "username";
        else baseType = "phoneNumber";

        // If we've already kept one index for this column, drop the duplicate
        if (seenBase.has(baseType)) {
          console.log(`🗑️ Dropping redundant index key: "${keyName}"`);
          await sequelize.query(`ALTER TABLE users DROP INDEX \`${keyName}\``);
        } else {
          seenBase.add(baseType);
        }
      }
    }
  } catch (err: any) {
    console.log("ℹ️ Skipping duplicate index cleanup:", err.message);
  }
}

async function startConnection() {
  try {
    // 1. Authenticate
    await sequelize.authenticate();
    console.log("🔗 Connection has been established successfully.");
    // 1.4. Clean up duplicate index keys generated by previous alter syncs
    await cleanupDuplicateIndexes();
    // 1.5. Clean up duplicate usernames before altering constraints
    await deduplicateUsernames();
    // 2. Sync with database
    // Note: Only uncomment the line below when there is a column/model modification.
    // Restart the server to sync the changes, then re-comment it and use the default sync.
    // await sequelize.sync({ alter: true });
    await sequelize.sync();
    console.log("👌 All models were synchronized successfully.");
    // 3. Backfill category columns for any existing blogs
    await backfillCategories();
    // 4. Start Server
    app.listen(process.env.PORT, (err) => {
      if (err) throw err;
      console.log("✅ Server is running on port: " + process.env.PORT);
      initCronJobs();
    });
  } catch (e) {
    console.error("Error occurred while starting the connection:", e);
    process.exit(1);
  }
}

startConnection()
  .then(() => {
    console.log(
      "✅ Database connection established and server started successfully.",
    );
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
