import React, { useState } from 'react';

interface FlowStep {
    id: number;
    title: string;
    icon: string;
    description: string;
    technicalDetails: string;
    visualization: React.ReactNode;
}

const AutomationRoadmap = () => {
    const [activeStep, setActiveStep] = useState(1);

    const automationSteps: FlowStep[] = [
        {
            id: 1,
            title: "Editor & Media Tracking",
            icon: "edit_note",
            description: "When writing blogs, the TipTap editor dynamically tracks images. The backend marks images embedded in the blog content as 'active' in MySQL, ensuring they are preserved.",
            technicalDetails: "On blog creation/update, a regex parser extracts image sources. A Sequelize transaction updates the status of matching records in the 'media' table to 'active' and links them to the blog ID.",
            visualization: (
                <div className="flex flex-col gap-4 p-6 bg-slate-50 dark:bg-slate-900/60 rounded-2xl border border-slate-200/50 dark:border-slate-800/80 font-mono text-xs text-slate-700 dark:text-slate-300">
                    <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-855 pb-2 mb-2">
                        <span className="text-indigo-500 font-bold">SQL TRANSACTION</span>
                        <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-500 text-[10px] uppercase font-bold">RUNNING</span>
                    </div>
                    <div>
                        <span className="text-slate-400">// Parse inline media assets</span>
                        <br />
                        <span className="text-blue-500">const</span> urls = extractImageSrcs(content);
                    </div>
                    <div>
                        <span className="text-slate-400">// Update media association</span>
                        <br />
                        <span className="text-blue-500">await</span> media.update(&#123; status: <span className="text-amber-500">'active'</span>, associatedBlogId: id &#125;, &#123; where: &#123; url: &#123; [Op.in]: urls &#125; &#125; &#125;);
                    </div>
                    <div className="flex items-center gap-2 mt-4 p-3 bg-emerald-500/5 rounded-xl border border-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-xs">
                        <span className="material-symbols-outlined text-[16px]">check_circle</span>
                        <span>Successfully linked uploaded media assets to Blog #{activeStep}</span>
                    </div>
                </div>
            )
        },
        {
            id: 2,
            title: "AI Art Director (Briefing)",
            icon: "psychology",
            description: "If a blog is created without any inline images, our AI pipeline triggers. The 'Art Director' analyzes the title and designs a creative visual prompt relevant to the topic.",
            technicalDetails: "The server sends a POST completions request to Pollinations AI using the 'mistral-small-3.2' model. Strict rules enforce the exclusion of scrambled text, codes, and literal/animal puns.",
            visualization: (
                <div className="flex flex-col gap-3 p-6 bg-slate-50 dark:bg-slate-900/60 rounded-2xl border border-slate-200/50 dark:border-slate-800/80 text-xs">
                    <div className="flex items-center gap-2 text-indigo-500 font-bold font-mono">
                        <span className="material-symbols-outlined text-sm">rocket_launch</span>
                        <span>MISTRAL-SMALL COMPLETIONS</span>
                    </div>
                    <div className="p-3 bg-slate-100 dark:bg-slate-950/65 rounded-xl text-slate-500 dark:text-slate-400 italic">
                        "Analyze the title: 'Node.js Event Loop'. Design a modern, text-free, abstract geometric composition. Avoid literal tools..."
                    </div>
                    <div className="flex items-center justify-center py-2">
                        <span className="material-symbols-outlined text-3xl animate-bounce text-primary dark:text-indigo-400">arrow_circle_down</span>
                    </div>
                    <div className="p-3 bg-indigo-500/5 rounded-xl border border-indigo-500/15 text-indigo-600 dark:text-indigo-400 font-semibold leading-relaxed">
                        "A sleek, futuristic cityscape under a night sky with glowing, interconnected nodes and streams of light weaving continuously..."
                    </div>
                </div>
            )
        },
        {
            id: 3,
            title: "AI Artist (Image Synthesis)",
            icon: "palette",
            description: "The visual concept generated by the Art Director is sent to the 'Artist' model. It renders a beautiful, 800x450 horizontal layout thumbnail.",
            technicalDetails: "The prompt brief is sent to Pollinations AI's keyless GET image generator with the 'flux' model, returning the raw image buffer instantly with noologo and private settings.",
            visualization: (
                <div className="flex flex-col gap-3 p-4 bg-slate-50 dark:bg-slate-900/60 rounded-2xl border border-slate-200/50 dark:border-slate-800/80 text-xs items-center justify-center">
                    <div className="w-full flex items-center justify-between font-mono text-[10px] text-slate-400 mb-1 border-b border-slate-200 dark:border-slate-855 pb-2">
                        <span>API ENDPOINT: IMAGE.POLLINATIONS.AI</span>
                        <span className="text-indigo-500">MODEL=FLUX</span>
                    </div>
                    <div className="relative w-full h-32 rounded-xl overflow-hidden shadow-inner group bg-slate-200 dark:bg-slate-950 flex items-center justify-center">
                        <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(99,102,241,0.1)_1px,transparent_1px),linear-gradient(to_bottom,rgba(99,102,241,0.1)_1px,transparent_1px)] bg-[size:1rem_1rem] animate-[pulse_2s_infinite]" />
                        <span className="material-symbols-outlined text-4xl text-indigo-400 animate-spin">cyclone</span>
                        <div className="absolute bottom-2 left-2 bg-slate-950/80 backdrop-blur-md px-2 py-0.5 rounded text-[10px] text-slate-200 font-mono">
                            rendering_brief.bin
                        </div>
                    </div>
                    <span className="text-slate-500 dark:text-slate-400 text-center font-medium mt-1">Generating 800x450 pixel canvas cover...</span>
                </div>
            )
        },
        {
            id: 4,
            title: "Cloud CDN Caching",
            icon: "cloud_upload",
            description: "Once the AI cover is synthesized, it is uploaded directly to Cloudinary. It gets cached globally, optimized, and served through a high-speed Content Delivery Network (CDN).",
            technicalDetails: "The server processes the fetched image response as an ArrayBuffer, wraps it in a Node Buffer, and executes the Cloudinary Uploader SDK stream into the 'blog_thumbnails' folder.",
            visualization: (
                <div className="flex flex-col gap-3 p-6 bg-slate-50 dark:bg-slate-900/60 rounded-2xl border border-slate-200/50 dark:border-slate-800/80 text-xs">
                    <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-855 pb-2 mb-2 font-mono">
                        <span className="text-blue-500 font-bold">CLOUDINARY UPLOAD</span>
                        <span className="text-slate-400">CDN</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded bg-indigo-500/10 flex items-center justify-center text-indigo-500">
                            <span className="material-symbols-outlined text-xl">upload_file</span>
                        </div>
                        <div className="flex-grow">
                            <div className="font-semibold text-slate-700 dark:text-slate-200">raw_thumbnail_buffer</div>
                            <div className="text-[10px] text-slate-400 font-mono">Size: ~254 KB</div>
                        </div>
                    </div>
                    <div className="flex items-center justify-center my-1">
                        <span className="material-symbols-outlined text-xl text-slate-300 animate-pulse">keyboard_double_arrow_down</span>
                    </div>
                    <div className="p-3 bg-emerald-500/5 rounded-xl border border-emerald-500/15 font-mono text-[10px] text-emerald-600 dark:text-emerald-400 truncate">
                        SECURE URL: https://res.cloudinary.com/blog_thumbnails/...
                    </div>
                </div>
            )
        },
        {
            id: 5,
            title: "Automated Cleanup Cron",
            icon: "cleaning_services",
            description: "To prevent media bloat and stay within free-tier storage limits, a background cleanup job automatically deletes orphaned images that are not associated with any active blog posts.",
            technicalDetails: "A Cron Job is scheduled using 'node-cron' to trigger daily at midnight. It queries the 'media' table for records with status 'pending' created over 2 hours ago, deletes them from Cloudinary, and drops the DB rows.",
            visualization: (
                <div className="flex flex-col gap-4 p-6 bg-slate-50 dark:bg-slate-900/60 rounded-2xl border border-slate-200/50 dark:border-slate-800/80 font-mono text-xs text-slate-700 dark:text-slate-300">
                    <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-855 pb-2 mb-2">
                        <span className="text-amber-500 font-bold">BACKGROUND CRON</span>
                        <span className="text-slate-400">0 0 * * * (Daily)</span>
                    </div>
                    <div>
                        <span className="text-slate-400">// Select pending orphaned media</span>
                        <br />
                        <span className="text-blue-500">const</span> orphans = <span className="text-blue-500">await</span> media.findAll(&#123; where: &#123; status: <span className="text-amber-500">'pending'</span>, createdAt: &#123; [Op.lt]: twoHoursAgo &#125; &#125; &#125;);
                    </div>
                    <div>
                        <span className="text-slate-400">// Purge from Cloudinary & DB</span>
                        <br />
                        <span className="text-blue-500">for</span> (const item of orphans) &#123;
                        <br />
                        &nbsp;&nbsp;<span className="text-blue-500">await</span> deleteFromCloudinary(item.publicId);
                        <br />
                        &nbsp;&nbsp;<span className="text-blue-500">await</span> item.destroy();
                        <br />
                        &#125;
                    </div>
                    <div className="flex items-center gap-2 mt-2 p-3 bg-amber-500/5 rounded-xl border border-amber-500/10 text-amber-600 dark:text-amber-400 text-xs">
                        <span className="material-symbols-outlined text-[16px]">history_toggle_off</span>
                        <span>Server optimized. Cleanup routine initialized successfully.</span>
                    </div>
                </div>
            )
        }
    ];

    return (
        <section className="flex flex-col gap-10">
            <div className="flex flex-col gap-2">
                <h2 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white">
                    Inside the Engine: Platform Automation
                </h2>
                <p className="text-slate-500 dark:text-slate-400 text-sm max-w-lg">
                    Click through the pipeline stages below to see how Showoff manages content styling, AI design decisions, and database optimizations behind the scenes.
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                {/* Navigation Tabs (Left 5 Cols) */}
                <div className="lg:col-span-5 flex flex-col gap-3">
                    {automationSteps.map((step) => {
                        const isActive = activeStep === step.id;
                        return (
                            <button
                                key={step.id}
                                onClick={() => setActiveStep(step.id)}
                                className={`flex items-center gap-4 p-4 rounded-xl border text-left transition-all group ${
                                    isActive
                                        ? 'bg-slate-900 border-slate-900 text-white dark:bg-slate-900 dark:border-slate-800'
                                        : 'bg-transparent border-slate-100 hover:border-slate-200 dark:border-slate-900 dark:hover:border-slate-800 text-slate-600 dark:text-slate-450 hover:text-slate-900 dark:hover:text-white'
                                }`}
                            >
                                <span className={`material-symbols-outlined p-2 rounded-lg text-lg transition-colors ${
                                    isActive 
                                        ? 'bg-primary/20 text-primary dark:bg-indigo-500/25 dark:text-indigo-400' 
                                        : 'bg-slate-50 dark:bg-slate-900 text-slate-400 group-hover:text-primary dark:group-hover:text-indigo-400'
                                }`}>
                                    {step.icon}
                                </span>
                                <div className="flex flex-col">
                                    <span className="font-semibold text-sm leading-snug">{step.title}</span>
                                    <span className={`text-[11px] mt-1 ${
                                        isActive ? 'text-slate-400' : 'text-slate-400 dark:text-slate-500'
                                    }`}>
                                        Stage 0{step.id}
                                    </span>
                                </div>
                            </button>
                        );
                    })}
                </div>

                {/* Interactive Visualizer Card (Right 7 Cols) */}
                <div className="lg:col-span-7 bg-surface-container-lowest dark:bg-slate-900 border border-outline-variant/30 dark:border-slate-800 rounded-3xl p-6 md:p-8 flex flex-col gap-6 shadow-sm min-h-[420px] justify-between transition-all duration-300">
                    {automationSteps.map((step) => {
                        if (step.id !== activeStep) return null;
                        return (
                            <div key={step.id} className="flex flex-col gap-6 animate-[fadeIn_0.3s_ease-out]">
                                <div className="flex flex-col gap-2">
                                    <div className="font-mono text-[10px] font-bold text-primary dark:text-indigo-400 tracking-widest uppercase">
                                        STAGE 0{step.id} // ACTIVE SCHEDULER
                                    </div>
                                    <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                                        {step.title}
                                    </h3>
                                    <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
                                        {step.description}
                                    </p>
                                </div>

                                {/* Visualization element */}
                                <div className="my-2">
                                    {step.visualization}
                                </div>

                                <div className="flex flex-col gap-2 border-t border-slate-105 dark:border-slate-800/80 pt-4">
                                    <div className="text-[11px] font-bold text-slate-400 dark:text-slate-550 uppercase tracking-wider font-mono">
                                        SYSTEM ARCHITECTURE DETAILS
                                    </div>
                                    <p className="text-slate-500 dark:text-slate-405 text-[11px] leading-relaxed">
                                        {step.technicalDetails}
                                    </p>
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
};

export default AutomationRoadmap;
