import * as React from 'react';
import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components';

interface ResetPasswordEmailProps {
  resetUrl: string;
  userEmail?: string;
}

export const ResetPasswordEmail = ({
  resetUrl,
  userEmail,
}: ResetPasswordEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>Reset your ShowOff account password</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={headerSection}>
            <Heading style={heading}>ShowOff</Heading>
            <Text style={subheading}>Developer Portfolio & Community Platform</Text>
          </Section>

          <Hr style={hr} />

          {/* Content */}
          <Section style={contentSection}>
            <Heading style={title}>Password Reset Request</Heading>
            <Text style={text}>
              Hi{userEmail ? ` (${userEmail})` : ''},
            </Text>
            <Text style={text}>
              We received a request to reset the password for your ShowOff account. Click the button below to establish a new password. This reset link is valid for <strong>5 minutes</strong>.
            </Text>

            {/* Action Button */}
            <Section style={buttonContainer}>
              <Button style={button} href={resetUrl}>
                Reset Password
              </Button>
            </Section>

            <Text style={secondaryText}>
              If the button above doesn't work, copy and paste the following link directly into your browser:
            </Text>
            <Text style={linkText}>
              <Link href={resetUrl} style={link}>
                {resetUrl}
              </Link>
            </Text>

            <Text style={text}>
              If you did not request a password reset, you can safely ignore this email. Your password will remain unchanged.
            </Text>
          </Section>

          <Hr style={hr} />

          {/* Footer */}
          <Section style={footerSection}>
            <Text style={footerText}>
              This email was automatically generated by ShowOff Platform. Please do not reply.
            </Text>
            <Text style={footerText}>
              © {new Date().getFullYear()} ShowOff. All rights reserved.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default ResetPasswordEmail;

// Inline styles for cross-client email rendering reliability
const main: React.CSSProperties = {
  backgroundColor: '#f8fafc',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif',
};

const container: React.CSSProperties = {
  margin: '0 auto',
  padding: '32px 20px',
  maxWidth: '580px',
};

const headerSection: React.CSSProperties = {
  textAlign: 'center' as const,
  paddingBottom: '16px',
};

const heading: React.CSSProperties = {
  fontSize: '28px',
  fontWeight: '800',
  color: '#4f46e5',
  margin: '0 0 4px 0',
  letterSpacing: '-0.5px',
};

const subheading: React.CSSProperties = {
  fontSize: '14px',
  color: '#64748b',
  margin: '0',
};

const hr: React.CSSProperties = {
  borderColor: '#e2e8f0',
  margin: '24px 0',
};

const contentSection: React.CSSProperties = {
  backgroundColor: '#ffffff',
  padding: '32px 28px',
  borderRadius: '12px',
  border: '1px solid #e2e8f0',
  boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.05)',
};

const title: React.CSSProperties = {
  fontSize: '20px',
  fontWeight: '700',
  color: '#0f172a',
  margin: '0 0 16px 0',
};

const text: React.CSSProperties = {
  fontSize: '15px',
  lineHeight: '1.6',
  color: '#334155',
  margin: '0 0 16px 0',
};

const buttonContainer: React.CSSProperties = {
  textAlign: 'center' as const,
  margin: '28px 0',
};

const button: React.CSSProperties = {
  backgroundColor: '#4f46e5',
  borderRadius: '8px',
  color: '#ffffff',
  fontSize: '15px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 32px',
  boxShadow: '0 4px 6px -1px rgba(79, 70, 229, 0.2)',
};

const secondaryText: React.CSSProperties = {
  fontSize: '13px',
  color: '#64748b',
  margin: '24px 0 8px 0',
};

const linkText: React.CSSProperties = {
  fontSize: '13px',
  margin: '0 0 20px 0',
  wordBreak: 'break-all' as const,
};

const link: React.CSSProperties = {
  color: '#4f46e5',
  textDecoration: 'underline',
};

const footerSection: React.CSSProperties = {
  textAlign: 'center' as const,
  paddingTop: '8px',
};

const footerText: React.CSSProperties = {
  fontSize: '12px',
  color: '#94a3b8',
  margin: '0 0 4px 0',
};
